# Generated by Django 6.1 on 2026-08-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_profilechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstaff',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
